#!/usr/bin/env bash
# Installs a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend dudegfa
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 35168-web-01 44.200.78.200:80 check
    server 35168-web-02 34.224.63.115:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart